<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Listener: Test Passed :sampletest]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="34202" started-at="2017-06-09T12:21:47Z" finished-at="2017-06-09T12:22:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34202" started-at="2017-06-09T12:21:47Z" finished-at="2017-06-09T12:22:21Z">
      <class name="com.ggktech.tests.sample">
        <test-method status="FAIL" signature="exceptionTestOne()[pri:0, instance:com.ggktech.tests.sample@56528192]" name="exceptionTestOne" duration-ms="5293" started-at="2017-06-09T17:51:47Z" finished-at="2017-06-09T17:51:52Z">
          <exception class="java.io.IOException">
            <full-stacktrace>
              <![CDATA[java.io.IOException
	at com.ggktech.tests.sample.exceptionTestOne(sample.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptionTestOne -->
        <test-method status="PASS" signature="sampletest()[pri:0, instance:com.ggktech.tests.sample@56528192]" name="sampletest" duration-ms="2683" started-at="2017-06-09T17:52:16Z" finished-at="2017-06-09T17:52:18Z">
          <reporter-output>
            <line>
              <![CDATA[Listener: Test Passed :sampletest]]>
            </line>
          </reporter-output>
        </test-method> <!-- sampletest -->
      </class> <!-- com.ggktech.tests.sample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
